FROM python:3.9-slim-bullseye as base
LABEL maintainer="Juan Rabadan <juan@arzion.com>"

RUN apt-get update \
    && apt-get install -y git ssh-client build-essential curl libpq-dev --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man \
    && apt-get clean \
    && useradd --create-home python \
    && mkdir -p /home/python/app && chown python:python -R /home/python

# set working directory
WORKDIR /home/python/app

USER python

ADD ./requirements-dev.txt /home/python/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

CMD flask run -h 0.0.0.0 -p 5000
